# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Atul Kakrana
tagline:          'A computational biologist den'
description:      'Computational biology, Genomics, High-performance computing, Bioinformatics and Systems Biology'
url:              http://atulkakrana.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/atulkakrana
